radar:
  id: 'intiaRadar'
  name: 'INTIA Method Radar'
  showName: false
  defaultColor: 'rgba(99, 110, 114, 1.0)'
  renderResolution: 410

sector:
  useColor: false
  showName: false
  nameOffset: 5

segment: 
  colorGradient: true
  colorGradientLimit: 1.66
  showName: true
  useIdAsHeadline: true
  firstSegmentRadiusPercent: 0.25
  padding: 4

blip:
  size: 30
  defaultColor: '#8395a7'
  margin: 2