radar:
  id: 'intiaRadar'
  name: 'Radar Name'
  showName: true
  showAllSectorsText: 'Alle Sektoren'
  legendDropdownText: 'Legende'
  defaultColor: 'rgba(255, 255, 255, 0)'
  renderResolution: 411

sector:
  useColor: false
  showName: false
  nameOffset: 5

segment: 
  colorGradient: false
  colorGradientLimit: 1.66
  showName: false
  showNameAsId: true
  padding: 4

blip:
  size: 34
  defaultColor: '#8395a7'
  margin: 2