radar:
  id: 'intiaRadar'
  name: 'INTIA Method Radar'
  defaultColor: 'rgba(99, 110, 114, 1.0)'
  renderResolution: 624 

sector:
  useColor: false
  showHeadline: true

segment: 
  colorGradient: false
  colorGradientLimit: 1.66
  showHeadline: true
  useIdAsHeadline: true
  firstSegmentRadiusPercent: 0.25
  padding: 4

blip:
  size: 34
  defaultColor: '#8395a7'
  margin: 2